refactor code

diff --git a/files/etc/init.d/S92motion b/files/etc/init.d/S92motion
--- a/files/etc/init.d/S92motion
+++ b/files/etc/init.d/S92motion
@@ -1,38 +1,33 @@
 #!/bin/sh
+# from microbe-web package.
 
-if [ -n "$(echo "hi3516cv100 hi3516av100" | sed -n "/\b$(ipcinfo --family)\b/p")" ]; then
-  echo "Motion detection is not supported on your camera!"
-  exit 1
-fi
+UNSUPPORTED="hi3516cv100 hi3516av100"
+[ -n "$(echo $UNSUPPORTED | sed -n "/\b$(ipcinfo --family)\b/p")" ] &&
+  echo "Motion detection is not supported on your camera!" && exit 1
 
-config_file="/etc/webui/motion.conf"
-if [ ! -f "$config_file" ]; then
-  echo "Config file $config_file not found!"
-  exit 2
-fi
-source $config_file
+# read config file
+_c="/etc/webui/motion.conf"
+[ ! -f "$_c" ] && echo "Config file $_c not found!" && exit 2
+source $_c
+unset _c
 
-if [ "true" != "$motion_enabled" ]; then
-  echo "Motion detection is disabled in config!"
-  exit 3
-fi
+[ "true" != "$motion_enabled" ] &&
+  echo "Motion detection is disabled in config!" && exit 3
 
 STOP_FILE=/tmp/motion.stop
 TEMPLATE="Motion detected in \d* regions"
 logread -f | grep "$TEMPLATE" | sed -E "s/.*($TEMPLATE).*/\\1/" | while read LINE; do
   [ "$(echo $LINE | cut -d' ' -f4)" -lt "$(( 51 - $motion_sensitivity ))" ] && continue
 
-  # rate-limit execution
+  # throttle execution
   [ -f "$STOP_FILE" ] && [ "$(date -r "$STOP_FILE" +%s)" -ge "$(( $(date +%s) - $motion_throttle ))" ] && continue
   touch "$STOP_FILE"
 
   # get a fresh snapshot
   snapshot4cron.sh -f
-  if [ $? -ne 0 ]; then
-    echo "Cannot get a snapshot"
-    exit 2
-  fi
+  [ $? -ne 0 ] && echo "Cannot get a snapshot" && exit 2
 
+  # send alerts
   [ "true" = "$motion_send2email"    ] && send2email.sh
   [ "true" = "$motion_send2ftp"      ] && send2ftp.sh
   [ "true" = "$motion_send2telegram" ] && send2telegram.sh
